version: '3'
services:
  server:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - ${DATABASE_PROVIDER}
      - ${CACHE_PROVIDER}
    environment:
      SERVER_PORT: ${SERVER_PORT}

      DEFAULT_SENDER_FROM: ${DEFAULT_SENDER_FROM}
      DEFAULT_SENDER_EMAIL: ${DEFAULT_SENDER_EMAIL}

      DATABASE_PROVIDER: ${DATABASE_PROVIDER}

      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

      QUEUE_PROVIDER: ${QUEUE_PROVIDER}
      QUEUE_NAME: ${QUEUE_NAME}

      SQS_CLIENT_VERSION: ${SQS_CLIENT_VERSION}
      SQS_CLIENT_REGION: ${SQS_CLIENT_REGION}
      SQS_CLIENT_KEY: ${SQS_CLIENT_KEY}
      SQS_CLIENT_SECRET: ${SQS_CLIENT_SECRET}

      INTEGRATION_EMAIL: ${INTEGRATION_EMAIL}
      INTEGRATION_SMS: ${INTEGRATION_SMS}
      INTEGRATION_PUSH: ${INTEGRATION_PUSH}
      INTEGRATION_CALLBACK: ${INTEGRATION_CALLBACK}
      INTEGRATION_CHAT: ${INTEGRATION_CHAT}

      # Integration 'smtp'
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_ENDPOINT: ${SMTP_ENDPOINT}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}

      # Integration 'aws'
      AWS_CLIENT_VERSION: ${AWS_CLIENT_VERSION}
      AWS_CLIENT_REGION: ${AWS_CLIENT_REGION}
      AWS_CLIENT_KEY: ${AWS_CLIENT_KEY}
      AWS_CLIENT_SECRET: ${AWS_CLIENT_SECRET}

      # Integration 'sts'
      STS_CLIENT_VERSION: ${STS_CLIENT_VERSION}
      STS_CLIENT_REGION: ${STS_CLIENT_REGION}
      STS_CLIENT_KEY: ${STS_CLIENT_KEY}
      STS_CLIENT_SECRET: ${STS_CLIENT_SECRET}
      STS_CLIENT_EXTERNAL_ID: ${STS_CLIENT_EXTERNAL_ID}
      STS_CLIENT_ARN: ${STS_CLIENT_ARN}
      STS_CLIENT_CACHE_TIMEOUT: ${STS_CLIENT_CACHE_TIMEOUT}

      # Integration 'http'
      HTTP_URL: ${HTTP_URL}

      # Integration 'slack'
      SLACK_WEBHOOK_URI: ${SLACK_WEBHOOK_URI}

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always

  redis:
    image: redis:3.2-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
