version: '3'
services:
  server:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - ${DATABASE_PROVIDER}
      - ${CACHE_PROVIDER}
    environment:
      SERVER_PORT: ${SERVER_PORT}

      DATABASE_PROVIDER: ${DATABASE_PROVIDER}

      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

      QUEUE_PROVIDER: ${QUEUE_PROVIDER}
      QUEUE_NAME: ${QUEUE_NAME}

      SQS_CLIENT_VERSION: ${SQS_CLIENT_VERSION}
      SQS_CLIENT_REGION: ${SQS_CLIENT_REGION}
      SQS_CLIENT_KEY: ${SQS_CLIENT_KEY}
      SQS_CLIENT_SECRET: ${SQS_CLIENT_SECRET}

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always

  redis:
    image: redis:3.2-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
